version: '3.8'

networks:
  fastapi_network:

services:
  db:
    image: postgres:15
    container_name: fastapi_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fastapi_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  fastapi:
    build: .
    container_name: fastapi_app
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 9000
    networks:
      - fastapi_network

volumes:
  postgres_data:
