"""whatsappv2

Revision ID: 4972f1ce2326
Revises: 
Create Date: 2025-03-03 15:00:22.666856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4972f1ce2326'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'USER', name='userrole'), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('search_history_limit', sa.String(length=10), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('business_searches',
    sa.Column('business_type', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('radius', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('min_rating', sa.Float(), nullable=True),
    sa.Column('max_price_level', sa.Float(), nullable=True),
    sa.Column('open_now', sa.String(length=5), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', name='searchstatus'), nullable=False),
    sa.Column('results_count', sa.Float(), nullable=True),
    sa.Column('error_message', sa.String(length=512), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.String(length=255), nullable=True),
    sa.Column('search_params', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('celery_task_id')
    )
    op.create_index('idx_search_location', 'business_searches', ['latitude', 'longitude'], unique=False)
    op.create_index('idx_search_params', 'business_searches', ['business_type', 'location', 'status'], unique=False)
    op.create_index('idx_search_status', 'business_searches', ['status', 'user_id'], unique=False)
    op.create_index(op.f('ix_business_searches_business_type'), 'business_searches', ['business_type'], unique=False)
    op.create_index(op.f('ix_business_searches_id'), 'business_searches', ['id'], unique=False)
    op.create_index(op.f('ix_business_searches_location'), 'business_searches', ['location'], unique=False)
    op.create_index(op.f('ix_business_searches_status'), 'business_searches', ['status'], unique=False)
    op.create_table('whatsapp_accounts',
    sa.Column('profile_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('INITIALIZED', 'PENDING', 'ACTIVE', 'ERROR', 'BLOCKED', name='whatsappaccountstatus'), nullable=False),
    sa.Column('profile_path', sa.String(length=500), nullable=True),
    sa.Column('account_metadata', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_accounts_id'), 'whatsapp_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_whatsapp_accounts_profile_name'), 'whatsapp_accounts', ['profile_name'], unique=True)
    op.create_table('business_data',
    sa.Column('place_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('formatted_address', sa.String(length=512), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('formatted_phone_number', sa.String(length=50), nullable=True),
    sa.Column('international_phone_number', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('weekday_text', sa.JSON(), nullable=True),
    sa.Column('reviews', sa.JSON(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('user_ratings_total', sa.Float(), nullable=True),
    sa.Column('price_level', sa.Float(), nullable=True),
    sa.Column('business_status', sa.String(length=50), nullable=True),
    sa.Column('search_text', sa.String(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('types', sa.JSON(), nullable=False),
    sa.Column('opening_hours', sa.JSON(), nullable=True),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('search_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.CheckConstraint('latitude >= -90 AND latitude <= 90'),
    sa.CheckConstraint('longitude >= -180 AND longitude <= 180'),
    sa.ForeignKeyConstraint(['search_id'], ['business_searches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_location', 'business_data', ['latitude', 'longitude'], unique=False)
    op.create_index('idx_search_category', 'business_data', ['category', 'search_text'], unique=False)
    op.create_index(op.f('ix_business_data_category'), 'business_data', ['category'], unique=False)
    op.create_index(op.f('ix_business_data_id'), 'business_data', ['id'], unique=False)
    op.create_index(op.f('ix_business_data_name'), 'business_data', ['name'], unique=False)
    op.create_index(op.f('ix_business_data_place_id'), 'business_data', ['place_id'], unique=True)
    op.create_index(op.f('ix_business_data_search_text'), 'business_data', ['search_text'], unique=False)
    op.create_table('whatsapp_messages',
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('recipient', sa.String(length=20), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'ERROR', name='whatsappmessagestatus'), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('message_metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['whatsapp_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_messages_id'), 'whatsapp_messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whatsapp_messages_id'), table_name='whatsapp_messages')
    op.drop_table('whatsapp_messages')
    op.drop_index(op.f('ix_business_data_search_text'), table_name='business_data')
    op.drop_index(op.f('ix_business_data_place_id'), table_name='business_data')
    op.drop_index(op.f('ix_business_data_name'), table_name='business_data')
    op.drop_index(op.f('ix_business_data_id'), table_name='business_data')
    op.drop_index(op.f('ix_business_data_category'), table_name='business_data')
    op.drop_index('idx_search_category', table_name='business_data')
    op.drop_index('idx_location', table_name='business_data')
    op.drop_table('business_data')
    op.drop_index(op.f('ix_whatsapp_accounts_profile_name'), table_name='whatsapp_accounts')
    op.drop_index(op.f('ix_whatsapp_accounts_id'), table_name='whatsapp_accounts')
    op.drop_table('whatsapp_accounts')
    op.drop_index(op.f('ix_business_searches_status'), table_name='business_searches')
    op.drop_index(op.f('ix_business_searches_location'), table_name='business_searches')
    op.drop_index(op.f('ix_business_searches_id'), table_name='business_searches')
    op.drop_index(op.f('ix_business_searches_business_type'), table_name='business_searches')
    op.drop_index('idx_search_status', table_name='business_searches')
    op.drop_index('idx_search_params', table_name='business_searches')
    op.drop_index('idx_search_location', table_name='business_searches')
    op.drop_table('business_searches')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
