"""update models for postgres

Revision ID: ff18da84a304
Revises: c63ba2f1bb4c
Create Date: 2025-02-12 20:18:03.579847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff18da84a304'
down_revision: Union[str, None] = 'c63ba2f1bb4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_searches', 'cached_results')
    op.add_column('users', sa.Column('search_history_limit', sa.String(length=10), nullable=True))
    op.drop_index('ix_users_username', table_name='users')
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'max_search_history')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'save_search_history')
    op.drop_column('users', 'username')
    op.drop_column('users', 'notification_preferences')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notification_preferences', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('save_search_history', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('max_search_history', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.drop_column('users', 'search_history_limit')
    op.add_column('business_searches', sa.Column('cached_results', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
